# Gateway configuration
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: http://inventory:8081
          predicates:
            - Path=/inventory/**
        - id: orders
          uri: http://orders:8082
          predicates:
            - Path=/orders/**
